
// Auto-generated by AutoPilot on 05-08-2023 at 19:20:51

const express = require('express');
const router = express.Router();

//This route will return a head or false when called
router.get('/flip', (req, res) => {
    let rand = Math.floor(Math.random() * 2); //Generates a random number between 0 and 1
    if (rand == 0) res.status(200).send("Heads"); //If random number is 0 send head
    else res.status(200).send("False"); //Else send false
});

module.exports = router;